services:

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis-1
      - redis-2
      - redis-3

  redis-1:
    image: redis:7

  redis-2:
    image: redis:7

  redis-3:
    image: redis:7
